services:
  frontend:
    container_name: haku-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # If running in browser, localhost refers to host machine.
      # If SSR, it might need to talk to backend container name.
      # Ideally usage of public env vars handles client side
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - haku-network

networks:
  haku-network:
    driver: bridge
    external: true
